name: Process Audio on Modal

on:
  push:
    paths:
      - 'input_scripts/*.txt'
  workflow_dispatch:

jobs:
  generate_voiceover:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Modal
        run: pip install modal

      - name: Run Modal Audio Job
        env:
          MODAL_TOKEN_ID: ${{ secrets.TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Dəyişən faylları tap
          changed_files=$(git diff --name-only HEAD^ HEAD | grep 'input_scripts/.*\.txt$' || true)
          
          if [ -z "$changed_files" ]; then
            echo "No new scripts found."
            exit 0
          fi

          for file in $changed_files; do
            python trigger_modal.py "$file"
          done

      - name: Commit and Push output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add output_voiceovers/*.wav
          git commit -m "Auto-generated voiceover from Modal [skip ci]" || echo "No changes to commit"
          git push
